# Generated by Django 3.2 on 2021-05-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymTeachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False},
        ),
    ]
