# Generated by Django 3.2 on 2021-05-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('mail', models.CharField(db_collation='utf8_general_ci', max_length=45)),
            ],
            options={
                'db_table': 'Person',
                'managed': False,
            },
        ),
    ]
