# Generated by Django 3.2 on 2021-06-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('month', models.IntegerField(db_column='Month')),
                ('year', models.IntegerField(db_column='Year')),
            ],
            options={
                'db_table': 'Schedule',
                'managed': False,
            },
        ),
    ]
