-- MySQL Script generated by MySQL Workbench
-- Sat Apr 10 20:12:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sI9eL5baMe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sI9eL5baMe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sI9eL5baMe` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `sI9eL5baMe` ;

-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Schedule` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Month` INT(11) NOT NULL,
  `Year` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Service` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Service` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(80) NOT NULL,
  `HourFee` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Person` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Person` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` INT(11) NOT NULL,
  `mail` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`TeacherCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`TeacherCategory` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`TeacherCategory` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Teacher` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TeacherCategory_ID` INT(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Teacher_Person1_idx` (`ID` ASC) VISIBLE,
  INDEX `fk_Teacher_TeacherCategory1_idx` (`TeacherCategory_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Person1`
    FOREIGN KEY (`ID`)
    REFERENCES `sI9eL5baMe`.`Person` (`ID`),
  CONSTRAINT `fk_Teacher_TeacherCategory1`
    FOREIGN KEY (`TeacherCategory_ID`)
    REFERENCES `sI9eL5baMe`.`TeacherCategory` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Activity` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Activity` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Capacity` INT(11) NOT NULL,
  `dayOfWeek` INT(11) NOT NULL,
  `StarTime` TIME NOT NULL,
  `EndTime` TIME NOT NULL,
  `Schedule_ID` INT(11) NOT NULL,
  `Service_ID` INT(11) NOT NULL,
  `Teacher_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Activity_Schedule1_idx` (`Schedule_ID` ASC) VISIBLE,
  INDEX `fk_Activity_Service1_idx` (`Service_ID` ASC) VISIBLE,
  INDEX `fk_Activity_Teacher1_idx` (`Teacher_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Activity_Schedule1`
    FOREIGN KEY (`Schedule_ID`)
    REFERENCES `sI9eL5baMe`.`Schedule` (`ID`),
  CONSTRAINT `fk_Activity_Service1`
    FOREIGN KEY (`Service_ID`)
    REFERENCES `sI9eL5baMe`.`Service` (`ID`),
  CONSTRAINT `fk_Activity_Teacher1`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `sI9eL5baMe`.`Teacher` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`ClientState`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`ClientState` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`ClientState` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Client` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Client` (
  `ID` INT(11) NOT NULL,
  `Balance` DECIMAL(15,2) NOT NULL,
  `ClientState_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Client_ClientStates1_idx` (`ClientState_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Client_ClientStates1`
    FOREIGN KEY (`ClientState_ID`)
    REFERENCES `sI9eL5baMe`.`ClientState` (`ID`),
  CONSTRAINT `fk_Client_Person1`
    FOREIGN KEY (`ID`)
    REFERENCES `sI9eL5baMe`.`Person` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Activity_has_Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Activity_has_Client` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Activity_has_Client` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Activity_ID` INT(11) NOT NULL,
  `Client_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Activity_has_Client_Client1_idx` (`Client_ID` ASC) VISIBLE,
  INDEX `fk_Activity_has_Client_Activity1_idx` (`Activity_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Activity_has_Client_Activity1`
    FOREIGN KEY (`Activity_ID`)
    REFERENCES `sI9eL5baMe`.`Activity` (`ID`),
  CONSTRAINT `fk_Activity_has_Client_Client1`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `sI9eL5baMe`.`Client` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Admin` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Admin` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Person1`
    FOREIGN KEY (`ID`)
    REFERENCES `sI9eL5baMe`.`Person` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`PayMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`PayMethod` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`PayMethod` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Bill` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Bill` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Paid` TINYINT(1) NOT NULL,
  `PaymentDay` DATE NULL DEFAULT NULL,
  `IssueDate` DATE NOT NULL,
  `Cost` DECIMAL(15,2) NOT NULL,
  `Activity_ID` INT(11) NOT NULL,
  `PayMethod_ID` INT(11) NOT NULL,
  `Client_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Bill_Activity1_idx` (`Activity_ID` ASC) VISIBLE,
  INDEX `fk_Bill_PayMethod1_idx` (`PayMethod_ID` ASC) VISIBLE,
  INDEX `fk_Bill_Client1_idx` (`Client_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bill_Activity1`
    FOREIGN KEY (`Activity_ID`)
    REFERENCES `sI9eL5baMe`.`Activity` (`ID`),
  CONSTRAINT `fk_Bill_Client1`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `sI9eL5baMe`.`Client` (`ID`),
  CONSTRAINT `fk_Bill_PayMethod1`
    FOREIGN KEY (`PayMethod_ID`)
    REFERENCES `sI9eL5baMe`.`PayMethod` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Config` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Config` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `EffectiveDate` DATE NOT NULL,
  `CapacityPercentage` DECIMAL(5,4) NOT NULL,
  `TimePerDay` JSON NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Gym`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Gym` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Gym` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `TuitionCost` DECIMAL(15,2) NOT NULL,
  `Config_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Gym_Config1_idx` (`Config_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Gym_Config1`
    FOREIGN KEY (`Config_ID`)
    REFERENCES `sI9eL5baMe`.`Config` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Room` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Room` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Capacity` INT(11) NOT NULL,
  `Gym_ID` INT(11) NOT NULL,
  `Schedule_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Room_Gym_idx` (`Gym_ID` ASC) VISIBLE,
  INDEX `fk_Room_Schedule1_idx` (`Schedule_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Room_Gym`
    FOREIGN KEY (`Gym_ID`)
    REFERENCES `sI9eL5baMe`.`Gym` (`ID`),
  CONSTRAINT `fk_Room_Schedule1`
    FOREIGN KEY (`Schedule_ID`)
    REFERENCES `sI9eL5baMe`.`Schedule` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sI9eL5baMe`.`Teacher_has_Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sI9eL5baMe`.`Teacher_has_Service` ;

CREATE TABLE IF NOT EXISTS `sI9eL5baMe`.`Teacher_has_Service` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Teacher_ID` INT(11) NOT NULL,
  `Service_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Teacher_has_Service_Service1_idx` (`Service_ID` ASC) VISIBLE,
  INDEX `fk_Teacher_has_Service_Teacher1_idx` (`Teacher_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_has_Service_Service1`
    FOREIGN KEY (`Service_ID`)
    REFERENCES `sI9eL5baMe`.`Service` (`ID`),
  CONSTRAINT `fk_Teacher_has_Service_Teacher1`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `sI9eL5baMe`.`Teacher` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
