# Generated by Django 3.2 on 2021-09-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBU',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(db_column='Capacity')),
                ('dayofweek', models.IntegerField(db_column='dayOfWeek')),
                ('dayofmonth', models.IntegerField(db_column='dayOfMonth')),
                ('startime', models.TimeField(db_column='StarTime')),
                ('endtime', models.TimeField(db_column='EndTime')),
                ('schedule', models.IntegerField(db_column='Schedule_ID')),
                ('service', models.IntegerField(db_column='Service_ID')),
                ('teacher', models.IntegerField(db_column='Teacher_ID')),
                ('creator', models.IntegerField(db_column='creator_ID')),
                ('state', models.IntegerField(db_column='State')),
            ],
            options={
                'db_table': 'Activity_backup',
                'managed': False,
            },
        ),
    ]
