# Generated by Django 3.2 on 2021-06-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymPersons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userofperson',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'UserOfPerson',
                'managed': False,
            },
        ),
    ]
