# Generated by Django 3.2 on 2021-06-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(db_column='Capacity')),
                ('dayofweek', models.IntegerField(db_column='dayOfWeek')),
                ('startime', models.TimeField(db_column='StarTime')),
                ('endtime', models.TimeField(db_column='EndTime')),
            ],
            options={
                'db_table': 'Activity',
                'managed': False,
            },
        ),
    ]
