# Generated by Django 3.2 on 2021-09-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('message', models.CharField(db_column='Message', max_length=150)),
            ],
            options={
                'db_table': 'Notifications',
                'managed': False,
            },
        ),
    ]
